#ifndef Locations
#define Locations

#define OS_ADDRESS_FUNC_TABLE   0x200

#define UC_DATA_SIGNATURE       "PMD CME"
#define UC_DATA_CMEVERSION      0x00010001
#define UC_OFFSET_SIGNATURE     0x00
#define UC_OFFSET_CMEVERSION    0x0C
#define UC_OFFSET_CHECKSUM      0x10
#define UC_OFFSET_SIZE          0x14
#define UC_OFFSET_NAME          0x18
#define UC_OFFSET_VERSION       0x1C
#define UC_OFFSET_DATE          0x20
#define UC_OFFSET_FUNC_START    0x40
#define UC_OFFSET_FUNC_TABLE    0x60
#define UC_ADDRESS_START        0x40000
#define UC_ADDRESS_END          0x7FFFF
#define UC_ADDRESS_SIGNATURE    (UC_ADDRESS_START + UC_OFFSET_SIGNATURE)
#define UC_ADDRESS_CMEVERSION   (UC_ADDRESS_START + UC_OFFSET_CMEVERSION)
#define UC_ADDRESS_DATE         (UC_ADDRESS_START + UC_OFFSET_DATE)
#define UC_ADDRESS_CHECKSUM     (UC_ADDRESS_START + UC_OFFSET_CHECKSUM)
#define UC_ADDRESS_SIZE         (UC_ADDRESS_START + UC_OFFSET_SIZE)
#define UC_ADDRESS_NAME         (UC_ADDRESS_START + UC_OFFSET_NAME)       // file name
#define UC_ADDRESS_VERSION      (UC_ADDRESS_START + UC_OFFSET_VERSION)    // file version
#define UC_ADDRESS_FUNC_START   (UC_ADDRESS_START + UC_OFFSET_FUNC_START) // startup function
#define UC_ADDRESS_FUNC_TABLE   (UC_ADDRESS_START + UC_OFFSET_FUNC_TABLE) // function table

#define UM_ADDRESS_START        0x04016000
#define UM_ADDRESS_END          0x04017FFF

#endif
